[Vale a pena traduzir para o portuguÃªs?]

This guide comes directly from the [10 Minute Guide to Pandas](https://pandas.pydata.org/pandas-docs/stable/10min.html) on the Pandas official website. I ported it into this kernel to make the code more accessible. This guide is geared towards beginners who haven't used Pandas before. It has great examples on how powerful Pandas can be. Enjoy!

### This is a short introduction to pandas, geared mainly for new users. You can see more complex recipes in the [Cookbook](https://pandas.pydata.org/pandas-docs/stable/cookbook.html#cookbook)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Object Creation
See the [Data Structure Intro section](Data Structure Intro section). Creating a Series by passing a list of values, letting pandas create a default integer index:

In [2]:
s = pd.Series([1,3,5,6,8])
s

0    1
1    3
2    5
3    6
4    8
dtype: int64

In [3]:
s = pd.Series([1,3,5,np.nan,6,8, 'nome'])
s

0       1
1       3
2       5
3     NaN
4       6
5       8
6    nome
dtype: object

Creating a [DataFrame](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html#pandas.DataFrame) by passing a numpy array, with a datetime index and labeled columns:

In [4]:
dates = pd.date_range('20141101', periods=6)
dates

DatetimeIndex(['2014-11-01', '2014-11-02', '2014-11-03', '2014-11-04',
               '2014-11-05', '2014-11-06'],
              dtype='datetime64[ns]', freq='D')

In [5]:
np.random.seed(123)

In [6]:
np.random.randn(6,4)

array([[-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654, -2.42667924, -0.42891263],
       [ 1.26593626, -0.8667404 , -0.67888615, -0.09470897],
       [ 1.49138963, -0.638902  , -0.44398196, -0.43435128],
       [ 2.20593008,  2.18678609,  1.0040539 ,  0.3861864 ],
       [ 0.73736858,  1.49073203, -0.93583387,  1.17582904]])

In [7]:
df = pd.DataFrame(np.random.randn(6,4), index=dates,columns=['one','two','three','four'])
df

                 one       two     three      four
2014-11-01 -1.253881 -0.637752  0.907105 -1.428681
2014-11-02 -0.140069 -0.861755 -0.255619 -2.798589
2014-11-03 -1.771533 -0.699877  0.927462 -0.173636
2014-11-04  0.002846  0.688223 -0.879536  0.283627
2014-11-05 -0.805367 -1.727669 -0.390900  0.573806
2014-11-06  0.338589 -0.011830  2.392365  0.412912

Creating a DataFrame by passing a dict of objects that can be converted to series-like.

In [12]:
df2 = pd.DataFrame({ 'A' : 1.,
                    'B' : pd.Timestamp('20130102'),
                    'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                    'D' : np.array([3] * 4,dtype='int32'),
                    'E' : pd.Categorical(["test","train","test","train"]),
                    'F' : 'foo' })
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

Having specific [dtypes](https://pandas.pydata.org/pandas-docs/stable/basics.html#basics-dtypes):

In [9]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object


# Viewing Data
See the [Basics section](https://pandas.pydata.org/pandas-docs/stable/basics.html#basics)
See the top & bottom rows of the frame

In [10]:
df.head()

                 one       two     three      four
2014-11-01 -1.253881 -0.637752  0.907105 -1.428681
2014-11-02 -0.140069 -0.861755 -0.255619 -2.798589
2014-11-03 -1.771533 -0.699877  0.927462 -0.173636
2014-11-04  0.002846  0.688223 -0.879536  0.283627
2014-11-05 -0.805367 -1.727669 -0.390900  0.573806

In [14]:
df.sample()

                 one       two     three      four
2014-11-01 -1.253881 -0.637752  0.907105 -1.428681

In [ ]:
df.tail(3)

                 one       two     three      four
2014-11-04  0.002846  0.688223 -0.879536  0.283627
2014-11-05 -0.805367 -1.727669 -0.390900  0.573806
2014-11-06  0.338589 -0.011830  2.392365  0.412912

Display the index, columns, and the underlying numpy data

In [ ]:
df.index

DatetimeIndex(['2014-11-01', '2014-11-02', '2014-11-03', '2014-11-04',
               '2014-11-05', '2014-11-06'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df.columns

Index(['one', 'two', 'three', 'four'], dtype='object')

In [ ]:
df.values

array([[-1.25388067, -0.6377515 ,  0.9071052 , -1.4286807 ],
       [-0.14006872, -0.8617549 , -0.25561937, -2.79858911],
       [-1.7715331 , -0.69987723,  0.92746243, -0.17363568],
       [ 0.00284592,  0.68822271, -0.87953634,  0.28362732],
       [-0.80536652, -1.72766949, -0.39089979,  0.57380586],
       [ 0.33858905, -0.01183049,  2.39236527,  0.41291216]])

Describe shows a quick statistic summary of your data

In [ ]:
df.describe()

            one       two     three      four
count  6.000000  6.000000  6.000000  6.000000
mean  -0.604902 -0.541777  0.450146 -0.521760
std    0.812156  0.816906  1.198530  1.330426
min   -1.771533 -1.727669 -0.879536 -2.798589
25%   -1.141752 -0.821285 -0.357080 -1.114919
50%   -0.472718 -0.668814  0.325743  0.054996
75%   -0.032883 -0.168311  0.922373  0.380591
max    0.338589  0.688223  2.392365  0.573806

Transposing your data

In [ ]:
df.T

       2014-11-01  2014-11-02  2014-11-03  2014-11-04  2014-11-05  2014-11-06
one     -1.253881   -0.140069   -1.771533    0.002846   -0.805367    0.338589
two     -0.637752   -0.861755   -0.699877    0.688223   -1.727669   -0.011830
three    0.907105   -0.255619    0.927462   -0.879536   -0.390900    2.392365
four    -1.428681   -2.798589   -0.173636    0.283627    0.573806    0.412912

Sorting by an axis (In this case, sorting the columns in reverse alphabetical order):

In [ ]:
df.sort_index(axis=1, ascending=False)

                 two     three       one      four
2014-11-01 -0.637752  0.907105 -1.253881 -1.428681
2014-11-02 -0.861755 -0.255619 -0.140069 -2.798589
2014-11-03 -0.699877  0.927462 -1.771533 -0.173636
2014-11-04  0.688223 -0.879536  0.002846  0.283627
2014-11-05 -1.727669 -0.390900 -0.805367  0.573806
2014-11-06 -0.011830  2.392365  0.338589  0.412912

Sorting by values

In [ ]:
df.sort_values(by='two')

                 one       two     three      four
2014-11-05 -0.805367 -1.727669 -0.390900  0.573806
2014-11-02 -0.140069 -0.861755 -0.255619 -2.798589
2014-11-03 -1.771533 -0.699877  0.927462 -0.173636
2014-11-01 -1.253881 -0.637752  0.907105 -1.428681
2014-11-06  0.338589 -0.011830  2.392365  0.412912
2014-11-04  0.002846  0.688223 -0.879536  0.283627

# Selection

Note While standard Python / Numpy expressions for selecting and setting are intuitive and come in handy for interactive work, for production code, we recommend the optimized pandas data access methods, .at, .iat, .loc, .iloc and .ix.
See the indexing documentation [Indexing and Selecting Data](https://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing) and [MultiIndex / Advanced Indexing](https://pandas.pydata.org/pandas-docs/stable/advanced.html#advanced)

## Getting

Selecting a single column, which yields a Series, equivalent to df.one

In [ ]:
df['one']

2014-11-01   -1.253881
2014-11-02   -0.140069
2014-11-03   -1.771533
2014-11-04    0.002846
2014-11-05   -0.805367
2014-11-06    0.338589
Freq: D, Name: one, dtype: float64

In [ ]:
df.one

2014-11-01   -1.253881
2014-11-02   -0.140069
2014-11-03   -1.771533
2014-11-04    0.002846
2014-11-05   -0.805367
2014-11-06    0.338589
Freq: D, Name: one, dtype: float64

Selecting via [], which slices the rows.

In [ ]:
df[0:3]

                 one       two     three      four
2014-11-01 -1.253881 -0.637752  0.907105 -1.428681
2014-11-02 -0.140069 -0.861755 -0.255619 -2.798589
2014-11-03 -1.771533 -0.699877  0.927462 -0.173636

In [ ]:
df['20141102':'20141104']

                 one       two     three      four
2014-11-02 -0.140069 -0.861755 -0.255619 -2.798589
2014-11-03 -1.771533 -0.699877  0.927462 -0.173636
2014-11-04  0.002846  0.688223 -0.879536  0.283627

## Selecting by Label

See more in[ Selection by Label](https://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-label)

For getting a cross section using a label

In [ ]:
df.loc[dates[0]]

Selecting on a multi-axis by label

In [ ]:
df.loc[:,['one','two']]

Showing label slicing, both endpoints are included

In [ ]:
df.loc['20141102':'20141104',['one','two']]

Reduction in the dimensions of the returned object

In [15]:
df.loc['20141102',['one','two']]

one   -0.140069
two   -0.861755
Name: 2014-11-02 00:00:00, dtype: float64

For getting a scalar value

In [ ]:
df.loc[dates[0],'one']

For getting fast access to a scalar (equiv to the prior method)

In [ ]:
df.at[dates[0],'one']

## Selection by Position

See more in [Selection by Position](Selection by Position)

Select via the position of the passed integers

In [ ]:
df.iloc[3]

By integer slices, acting similar to numpy/python

By lists of integer position locations, similar to the numpy/python style

In [ ]:
df.iloc[[1,2,4],[0,2]]

For slicing rows explicitly

In [ ]:
df.iloc[1:3,:]

For slicing columns explicitly

In [ ]:
df.iloc[:,1:3]

For getting a value explicitly

In [ ]:
df.iloc[1,1]

For getting fast access to a scalar (equiv to the prior method)

In [ ]:
df.iat[0,0]

## Boolean Indexing
Using a single columnâs values to select data.

In [ ]:
df[df.one > 0.5]

In [ ]:
df[df.cargo == 'prefeito']

Selecting values from a DataFrame where a boolean condition is met.

In [ ]:
df[df>0]

Using the isin method for filtering:

In [16]:
df2 = df.copy()
df2['five'] = ['one', 'one','two','three','four','three']
df2

                 one       two     three      four   five
2014-11-01 -1.253881 -0.637752  0.907105 -1.428681    one
2014-11-02 -0.140069 -0.861755 -0.255619 -2.798589    one
2014-11-03 -1.771533 -0.699877  0.927462 -0.173636    two
2014-11-04  0.002846  0.688223 -0.879536  0.283627  three
2014-11-05 -0.805367 -1.727669 -0.390900  0.573806   four
2014-11-06  0.338589 -0.011830  2.392365  0.412912  three

In [ ]:
df2[df2['five'].isin(['two','four'])]

## Setting
Setting a new column automatically aligns the data by the indexes

In [ ]:
s1 = pd.Series([1,2,3,4,5,6], index=pd.date_range('20141101', periods=6))
s1

In [ ]:
df['six'] = s1
df

Setting values by label:

In [17]:
df.at[dates[0],'one'] = 0
df

                 one       two     three      four
2014-11-01  0.000000 -0.637752  0.907105 -1.428681
2014-11-02 -0.140069 -0.861755 -0.255619 -2.798589
2014-11-03 -1.771533 -0.699877  0.927462 -0.173636
2014-11-04  0.002846  0.688223 -0.879536  0.283627
2014-11-05 -0.805367 -1.727669 -0.390900  0.573806
2014-11-06  0.338589 -0.011830  2.392365  0.412912

Setting values by position:

In [ ]:
df.iat[0,1] = 0
df

In [ ]:
df.loc[:,'four'] = np.array([5] * len(df))
df

A where operation with setting.

In [ ]:
df2 = df.copy()
df2[df2 > 0] = -df2
df2

## Missing Data
pandas primarily uses the value np.nan to represent missing data. It is by default not included in computations. See the [Missing Data section](https://pandas.pydata.org/pandas-docs/stable/missing_data.html#missing-data)

Reindexing allows you to change/add/delete the index on a specified axis. This returns a copy of the data.

In [ ]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ['E'])
df1.loc[dates[0]:dates[1],'E'] = 1
df1

To drop any rows that have missing data:

In [ ]:
df1.dropna(how='any')

Filling missing data:

In [ ]:
df1.fillna(value=5)

## Operations
See the [Basic section on Binary Ops](https://pandas.pydata.org/pandas-docs/stable/basics.html#basics-binop)

### Stats
Operations in general *exclude* missing data.

Performing a descriptive statistic:

In [ ]:
df.mean()

Same operation on the other axis:

In [ ]:
df.mean(1)

Operating with objects that have different dimensionality and need alignment. In addition, pandas automatically broadcasts along the specified dimension. The following code also shifts the data vertically, leaving NaN values in the unoccupied spaces

In [ ]:
s = pd.Series([1,3,5,np.nan,6,8], index=dates).shift(2)
s

In [ ]:
df.sub(s, axis='index')

### Apply
Applying functions to the data

In [ ]:
df.apply(np.cumsum)

### Histogramming 
See more at [Histogramming and Discretization](https://pandas.pydata.org/pandas-docs/stable/basics.html#basics-discretization)

In [ ]:
s = pd.Series(np.random.randint(0, 7, size=10))
s

In [ ]:
s.value_counts()

### String Methods
Series is equipped with a set of string processing methods in the str attribute that make it easy to operate on each element of the array, as in the code snippet below. Note that pattern-matching in str generally uses [regular expressions](https://docs.python.org/2/library/re.html) by default (and in some cases always uses them). See more at [Vectorized String Methods](https://pandas.pydata.org/pandas-docs/stable/text.html#text-string-methods).

In [ ]:
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])

In [ ]:
s.str.lower()

# Merge
### Concat
pandas provides various facilities for easily combining together Series, DataFrame, and Panel objects with various kinds of set logic for the indexes and relational algebra functionality in the case of join / merge-type operations.

See the [Merging section](https://pandas.pydata.org/pandas-docs/stable/merging.html#merging)

Concatenating pandas objects together with [concat()](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.concat.html#pandas.concat):

In [ ]:
df = pd.DataFrame(np.random.randn(10, 4))
df

In [ ]:
#break it into pieces:
pieces = [df[:3], df[3:7], df[7:]]
pieces

In [ ]:
pd.concat(pieces)

### Join

SQL style merges. See the [Database style joining](https://pandas.pydata.org/pandas-docs/stable/merging.html#merging-join)

In [ ]:
left = pd.DataFrame({'key': ['foo', 'foo'], 'lval': [1, 2]})
left

In [ ]:
right = pd.DataFrame({'key': ['foo', 'foo'], 'rval': [4, 5]})
right

In [ ]:
pd.merge(left,right,on='key')

Another example that can be given is:

In [ ]:
left = pd.DataFrame({'key': ['foo', 'bar'], 'lval': [1, 2]})
left

In [ ]:
right = pd.DataFrame({'key': ['foo', 'bar'], 'rval': [4, 5]})
right

In [ ]:
pd.merge(left, right, on='key')

### Append
Append rows to a dataframe. See the [Appending](https://pandas.pydata.org/pandas-docs/stable/merging.html#merging-concatenation)

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4), columns=['A','B','C','D'])
df

In [ ]:
s = df.iloc[3]
s

In [ ]:
df.append(s,ignore_index=True)

# Grouping
By âgroup byâ we are referring to a process involving one or more of the following steps

Splitting the data into groups based on some criteria
Applying a function to each group independently
Combining the results into a data structure

See the [Grouping section](https://pandas.pydata.org/pandas-docs/stable/groupby.html#groupby)

In [ ]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
   ....:                           'foo', 'bar', 'foo', 'foo'],
   ....:                    'B' : ['one', 'one', 'two', 'three',
   ....:                           'two', 'two', 'one', 'three'],
   ....:                    'C' : np.random.randn(8),
   ....:                    'D' : np.random.randn(8)})
df

Grouping and then applying a function sum to the resulting groups.

In [ ]:
df.groupby('A').sum()

Grouping by multiple columns forms a hierarchical index, which we then apply the function.

In [ ]:
df.groupby(['A','B']).sum()

# Reshaping
See the sections on [Hierarchical Indexing](https://pandas.pydata.org/pandas-docs/stable/advanced.html#advanced-hierarchical) and [Reshaping](https://pandas.pydata.org/pandas-docs/stable/reshaping.html#reshaping-stacking).

### Stack

In [19]:
tuples = list(zip(*[['bar', 'bar', 'baz', 'baz',
   ....:                      'foo', 'foo', 'qux', 'qux'],
   ....:                     ['one', 'two', 'one', 'two',
   ....:                      'one', 'two', 'one', 'two']]))
tuples

[('bar', 'one'),
 ('bar', 'two'),
 ('baz', 'one'),
 ('baz', 'two'),
 ('foo', 'one'),
 ('foo', 'two'),
 ('qux', 'one'),
 ('qux', 'two')]

In [20]:
index = pd.MultiIndex.from_tuples(tuples, names=['first', 'second'])
index

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

In [ ]:
df = pd.DataFrame(np.random.randn(8, 2), index=index, columns=['A', 'B'])
df

The [stack()](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.stack.html#pandas.DataFrame.stack) method âcompressesâ a level in the DataFrameâs columns.

In [ ]:
stacked = df.stack()
stacked

With a âstackedâ DataFrame or Series (having a MultiIndex as the index), the inverse operation of [stack()](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.stack.html#pandas.DataFrame.stack) is [unstack()](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.unstack.html#pandas.DataFrame.unstack), which by default unstacks the last level:

In [ ]:
stacked.unstack()

In [ ]:
stacked.unstack(1)

In [ ]:
stacked.unstack(0)

### Pivot Tables
See the section on [Pivot Tables](https://pandas.pydata.org/pandas-docs/stable/reshaping.html#reshaping-pivot).

In [21]:
df = pd.DataFrame({'A' : ['one', 'one', 'two', 'three'] * 3,
   .....:                    'B' : ['A', 'B', 'C'] * 4,
   .....:                    'C' : ['foo', 'foo', 'foo', 'bar', 'bar', 'bar'] * 2,
   .....:                    'D' : np.random.randn(12),
   .....:                    'E' : np.random.randn(12)})
df

        A  B    C         D         E
0     one  A  foo -0.520282 -1.486301
1     one  B  foo -1.698000 -0.029363
2     two  C  foo  0.768126 -1.237142
3   three  A  bar  0.393603  0.075986
4     one  B  bar -0.317174 -1.945198
5     one  C  bar -1.702728 -0.234840
6     two  A  foo  0.738600 -1.814567
7   three  B  foo -0.507776  0.059636
8     one  C  foo  0.227991 -0.397631
9     one  A  bar -1.740421  0.267998
10    two  B  bar -0.534505  0.890952
11  three  C  bar -0.937749  0.025341

We can produce pivot tables from this data very easily:

In [ ]:
pd.pivot_table(df, values='D', index=['A', 'B'], columns=['C'])

# Time Series
pandas has simple, powerful, and efficient functionality for performing resampling operations during frequency conversion (e.g., converting secondly data into 5-minutely data). This is extremely common in, but not limited to, financial applications. See the [Time Series section](https://pandas.pydata.org/pandas-docs/stable/timeseries.html#timeseries).

In [ ]:
rng = pd.date_range('1/1/2017', periods=100, freq='S')
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)
ts.resample('5Min').sum()

Time zone representation

In [ ]:
rng = pd.date_range('3/6/2017 00:00', periods=5, freq='D')
ts = pd.Series(np.random.randn(len(rng)), rng)
ts

In [ ]:
ts_utc = ts.tz_localize('UTC')
ts_utc

Convert to another time zone

In [ ]:
ts_utc.tz_convert('US/Eastern')

Converting between time span representations

In [ ]:
rng = pd.date_range('1/1/2012', periods=5, freq='M')
ts = pd.Series(np.random.randn(len(rng)), index=rng)
ts

In [ ]:
ps = ts.to_period('M')
ps

In [ ]:
ps.to_timestamp()

Converting between period and timestamp enables some convenient arithmetic functions to be used. In the following example, we convert a quarterly frequency with year ending in November to 9am of the end of the month following the quarter end:

In [ ]:
prng = pd.period_range('1990Q1', '2000Q4', freq='Q-NOV')
ts = pd.Series(np.random.randn(len(prng)), prng)
ts.index = (prng.asfreq('M', 'e') + 1).asfreq('H', 's') + 9
ts.head()

# Categoricals
pandas can include categorical data in a DataFrame. For full docs, see the [categorical introduction](https://pandas.pydata.org/pandas-docs/stable/categorical.html#categorical) and the [API documentation](https://pandas.pydata.org/pandas-docs/stable/api.html#api-categorical).

In [ ]:
df = pd.DataFrame({"id":[1,2,3,4,5,6], "raw_grade":['a', 'b', 'b', 'a', 'a', 'e']})
df

Convert the raw grades to a categorical data type:

In [ ]:
df["grade"] = df["raw_grade"].astype("category")
df["grade"]

Rename the categories to more meaningful names (assigning to Series.cat.categories is inplace!)

In [ ]:
df["grade"].cat.categories = ["very good", "good", "very bad"]

Reorder the categories and simultaneously add the missing categories (methods under Series .cat return a new Series per default).

In [ ]:
df["grade"] = df["grade"].cat.set_categories(["very bad", "bad", "medium", "good", "very good"])
df["grade"]

Sorting is per order in the categories, not lexical order.

In [ ]:
df.sort_values(by="grade")

Grouping by a categorical column shows also empty categories.

In [ ]:
df.groupby("grade").size()

# Plotting
[Plotting](https://pandas.pydata.org/pandas-docs/stable/visualization.html#visualization) docs

In [ ]:
ts = pd.Series(np.random.randn(1000), index=pd.date_range('1/1/2000', periods=1000))
ts = ts.cumsum()
ts.plot()

On DataFrame, plot() is a convenience to plot all of the columns with labels:

In [ ]:
df = pd.DataFrame(np.random.randn(1000, 4), index=ts.index,
   .....:                   columns=['A', 'B', 'C', 'D'])
df = df.cumsum()
plt.figure(); df.plot(); plt.legend(loc='best')

# Getting Data In/Out
### CSV
[Writing to a csv file](https://pandas.pydata.org/pandas-docs/stable/io.html#io-store-in-csv).

In [ ]:
df.to_csv('foo.csv')

In [ ]:
pd.read_csv('foo.csv')

### HDF5
Reading and writing to [HDFStores](https://pandas.pydata.org/pandas-docs/stable/io.html#io-hdf5).

Writing to a HDF5 Store:

In [ ]:
df.to_hdf('foo.h5','df')

Reading from a HDF5 Store:

In [ ]:
pd.read_hdf('foo.h5','df')

### Excel
Reading and writing to [MS Excel](https://pandas.pydata.org/pandas-docs/stable/io.html#io-excel).

Writing to an excel file:

In [ ]:
df.to_excel('foo.xlsx', sheet_name='Sheet1')

Reading from an excel file:

In [ ]:
pd.read_excel('foo.xlsx', 'Sheet1', index_col=None, na_values=['NA'])

# Gotchas
If you are trying an operation and you see an exception like:

In [ ]:
if pd.Series([False, True, False]):
    print("I was true")

See[ Comparisons](https://pandas.pydata.org/pandas-docs/stable/basics.html#basics-compare) for an explanation and what to do.

See [Gotchas](https://pandas.pydata.org/pandas-docs/stable/gotchas.html#gotchas) as well.

## AdiÃ§Ãµes

Utilizando esse caderno jupyter, sugiro executar as cÃ©lulas com cÃ³digo ilustrando as funcionalidades de pandas e realizar seus prÃ³prios experimentos, alterando parÃ¢metros ou pesquisando a documentaÃ§Ã£o das funÃ§Ãµes apresentadas.

Ã legal tambÃ©m ter uma fonte de pequenos conjuntos de dados, para poder testar funÃ§Ãµes ou aplicar algum conceito de anÃ¡lise.
Para isso, o pacote seaborn tem funÃ§Ãµes para importar alguns datasets:

In [ ]:
# Exemplos de "toy data sets" para se exercitar 
import seaborn as sns
print(sns.get_dataset_names())

# Infelizmente, esses data sets nÃ£o estÃ£o diretamente presentes no pacote seaborn, mas precisam ser baixados
# por uma conexÃ£o aberta Ã  internet. O que nÃ£o Ã© o caso para o kaggle, que bloqueia acessos http.
# Resultado esperado:
# ['anscombe', 'attention', 'brain_networks', 'car_crashes', 'dots', 'exercise', 'flights', 'fmri',
# 'gammas', 'iris', 'planets', 'tips', 'titanic']

df = sns.load_dataset('iris')
df.sample(10)